ImportError: No module named 'sklearn'

In [17]:
import tensorflow as tf
import numpy as np

sequence_length = 32
num_classes = 5

In [47]:
x = tf.placeholder(tf.float32, [None, sequence_length])
y = tf.placeholder(tf.float32, [None, num_classes])

y_pred = tf.contrib.layers.fully_connected(x, num_classes, activation_fn=None)

loss = tf.nn.sigmoid_cross_entropy_with_logits(y_pred, y)
loss = tf.reduce_mean(loss)

In [49]:
opt = tf.train.GradientDescentOptimizer(.05).minimize(loss)
sess = tf.InteractiveSession()

tf.global_variables_initializer().run()
x_feed = np.random.randint(2, size=(10, sequence_length))
y_feed = np.ones((10, num_classes))
y_feed[:, :2] = 0

for _ in range(3000):
    l, _ = sess.run([loss, opt], {x:x_feed, y:y_feed})

print(y_pred.eval({x:x_feed}))    
print(tf.sigmoid(y_pred).eval({x:x_feed}))



[[-5.66466618 -5.33471966  5.61610889  5.74477386  5.23424196]
 [-5.12271786 -5.18986225  5.15170574  4.63193798  5.47085857]
 [-4.44484997 -4.28440189  4.33090925  4.93728781  4.42050457]
 [-5.97144604 -5.97300434  5.2774663   5.21949577  5.30353832]
 [-6.35644388 -7.24684334  6.5868907   6.51005316  7.60603905]
 [-5.97695827 -7.59464645  7.92811441  6.27352762  6.9164257 ]
 [-5.97029495 -6.93450499  6.33861065  6.13938856  7.49371624]
 [-5.7572155  -5.64999485  5.86985111  5.77153587  5.60443211]
 [-6.00291729 -4.93190336  5.37128305  6.03584576  5.52750587]
 [-5.50127697 -5.89733267  5.62496424  5.88467932  5.15043449]]
[[  3.45433084e-03   4.79812827e-03   9.96374428e-01   9.96810734e-01
    9.94697332e-01]
 [  5.92449401e-03   5.54189086e-03   9.94243801e-01   9.90358055e-01
    9.95810032e-01]
 [  1.16026653e-02   1.35945044e-02   9.87015247e-01   9.92877066e-01
    9.88114715e-01]
 [  2.54406175e-03   2.54011038e-03   9.94920552e-01   9.94619012e-01
    9.95050609e-01]
 [  1.732

In [58]:
indices = [1, 4, 6]

oh = tf.one_hot(indices, 7)
tf.reduce_max(oh, 0).eval()

array([ 0.,  1.,  0.,  0.,  1.,  0.,  1.], dtype=float32)